### ISSUE TITLE
This should not be public

### ISSUE THREAD

**Issue by davechurchill** [srb806/4770#1]

**Comment by AlCollins** [comment]
Thanks for the comment. I did all the documentation for this group pretty well by myself and just leaving blanks for the other group members to fill in. We got full marks on all of them I believe. Unfortunately I was excluded from the coding of this project. When we assigned tasks I was told I was told that I was too old and that I should not get a part. I guess they were not joking because no one at all showed up for any meetings. It was just me who had to take time off work to show up for a meeting that no one attends ever and then have to make up that time off work that night. Most of the students would harrass me saying that I have stds and sleep with prostitutes. THis was not the only project that I was excluded from. Attending MUN computer Science was terrible for me. I'm not sure if this is hurting my job chances, but I have been unemployed for almost 3 years now. During this pandemic I have no EI, no job, no CERB, just nothing. I also just destroyed my savings again to get a second University degree and have a ton of student loans and lines of credit. Do you have any advice how I can land a job in this field? Do you know of anyone looking for a programmer who is starting out?

**Comment by davechurchill** [comment]
The MUN computer science discord channel may be able to help you with job opportunities, unfortunately I can't do much for you when it comes to landing a job. Lots of placed in St. John's are hiring. 

https://muncompsci.ca/
